use_frameworks!
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
target 'XVIEWAvdioManager_Example' do
  pod 'XVIEWAvdioManager', :path => '../'

  target 'XVIEWAvdioManager_Tests' do
    inherit! :search_paths

    
  end
end
